project:
  type: website

website:
  title: "Fourth Line Analytics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/cincysam6
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

